/*
 * @Author: wanghh
 * @Date: 2024-03-18 09:35:07
 * @LastEditors: wanghh
 * @LastEditTime: 2024-03-18 11:12:48
 * @Description:
 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * <head>
 *  <title>Create Next App</title>
 *  <description>Generated by create next app</description>
 * </head>
 * 
 * 
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
